export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const LOGOUT = "LOGOUT";

export const LOAD_PICTURE_SUCCESS = "LOAD_PICTURE_SUCCESS";

export const LOAD_IMAGE_SUCCESS = "LOAD_IMAGE_SUCCESS";
export const LOAD_IMAGE_FAIL = "LOAD_IMAGE_FAIL";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const POST_DEAL_SUCCESS = "POST_DEAL_SUCCESS";
export const POST_DEAL_FAIL = "POST_DEAL_FAIL";

export const GET_ALL_DEALS_SUCCESS = "GET_ALL_DEALS_SUCCESS";
export const GET_ALL_DEALS_FAIL = "GET_ALL_DEALS_FAIL";

export const POST_DISCUSSION_SUCCESS = "POST_DISCUSSION_SUCCESS";
export const POST_DISCUSSION_FAIL = "POST_DISCUSSION_FAIL";

export const GET_ALL_DISCUSSIONS_SUCCESS = "GET_ALL_DISCUSSIONS_SUCCESS";
export const GET_ALL_DISCUSSIONS_FAIL = "GET_ALL_DISCUSSIONS_FAIL";

export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const UPDATE_PROFILE_PASSWORD_SUCCESS =
  "UPDATE_PROFILE_PASSWORD_SUCCESS";
export const UPDATE_PROFILE_PASSWORD_FAIL = "UPDATE_PROFILE_PASSWORD_FAIL";

export const DELETE_PROFILE_SUCCESS = "DELETE_PROFILE_SUCCESS";
export const DELETE_PROFILE_FAIL = "DELETE_PROFILE_FAIL";

export const GET_USER_DEALS_SUCCESS = "GET_USER_DEALS_SUCCESS";
export const GET_USER_DEALS_FAIL = "GET_USER_DEALS_FAIL";

export const GET_USER_DISCUSSIONS_SUCCESS = "GET_USER_DISCUSSIONS_SUCCESS";
export const GET_USER_DISCUSSIONS_FAIL = "GET_USER_DISCUSSIONS_FAIL";

export const DELETE_USER_DEAL_FAIL = "DELETE_USER_DEAL_FAIL";
export const DELETE_USER_DEAL_SUCCESS = "DELETE_USER_DEAL_SUCCESS";

export const DELETE_USER_DISCUSSION_FAIL = "DELETE_USER_DISCUSSION_FAIL";
export const DELETE_USER_DISCUSSION_SUCCESS = "DELETE_USER_DISCUSSION_SUCCESS";

export const GET_DEAL_FAIL = "GET_DEAL_FAIL";
export const GET_DEAL_SUCCESS = "GET_DEAL_SUCCESS";

export const POST_DEAL_COMMENT_SUCCESS = "POST_DEAL_COMMENT_SUCCESS";
export const POST_DEAL_COMMENT_FAIL = "POST_DEAL_COMMENT_FAIL";

export const GET_DEAL_COMMENT_SUCCESS = "GET_DEAL_COMMENT_SUCCESS";
export const GET_DEAL_COMMENT_FAIL = "GET_DEAL_COMMENT_FAIL";

export const GET_DISCUSSION_SUCCESS = "GET_DISCUSSION_SUCCESS";
export const GET_DISCUSSION_FAIL = "GET_DISCUSSION_FAIL";

export const DELETE_USER_DISCUSSIONS_SUCCESS =
  "DELETE_USER_DISCUSSIONS_SUCCESS";
export const DELETE_USER_DISCUSSIONS_FAIL = "DELETE_USER_DISCUSSIONS_FAIL";

export const DELETE_USER_DEALS_SUCCESS = "DELETE_USER_DEALS_SUCCESS";
export const DELETE_USER_DEALS_FAIL = "DELETE_USER_DEALS_FAIL";

export const POST_DISCUSSION_COMMENT_SUCCESS =
  "POST_DISCUSSION_COMMENT_SUCCESS";
export const POST_DISCUSSION_COMMENT_FAIL = "POST_DISCUSSION_COMMENT_FAIL";

export const GET_DISCUSSION_COMMENT_SUCCESS = "GET_DISCUSSION_COMMENT_SUCCESS";
export const GET_DISCUSSION_COMMENT_FAIL = "GET_DISCUSSION_COMMENT_FAIL";

export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_FAIL = "GET_USER_INFO_FAIL";

export const INIT_STATE = "INIT_STATE";

export const GET_USER_PROFILE_DEALS_SUCCESS = "GET_USER_PROFILE_DEALS_SUCCESS";
export const GET_USER_PROFILE_DEALS_FAIL = "GET_USER_PROFILE_DEALS_FAIL";

export const GET_USER_PROFILE_DISCUSSIONS_SUCCESS =
  "GET_USER_PROFILE_DISCUSSIONS_SUCCESS";
export const GET_USER_PROFILE_DISCUSSIONS_FAIL =
  "GET_USER_PROFILE_DISCUSSIONS_FAIL";

export const GET_FOOTER_DEALS_SUCCESS = "GET_FOOTER_DEALS_SUCCESS";
export const GET_FOOTER_DEALS_FAIL = "GET_FOOTER_DEALS_FAIL";

export const GET_FOOTER_USERS_SUCCESS = "GET_FOOTER_USERS_SUCCESS";
export const GET_FOOTER_USERS_FAIL = "GET_FOOTER_USERS_FAIL";

export const GET_FOOTER_DISCUSSIONS_SUCCESS = "GET_FOOTER_DISCUSSIONS_SUCCESS";
export const GET_FOOTER_DISCUSSIONS_FAIL = "GET_FOOTER_DISCUSSIONS_FAIL";

export const GET_FOOTER_COMMENTS_DEALS_SUCCESS =
  "GET_FOOTER_COMMENTS_DEALS_SUCCESS";
export const GET_FOOTER_COMMENTS_DEALS_FAIL = "GET_FOOTER_COMMENTS_DEALS_FAIL";

export const GET_FOOTER_COMMENTS_DISCUSSIONS_SUCCESS =
  "GET_FOOTER_COMMENTS_DISCUSSIONS_SUCCESS";
export const GET_FOOTER_COMMENTS_DISCUSSIONS_FAIL =
  "GET_FOOTER_COMMENTS_DISCUSSIONS_FAIL";

export const GET_FOOTER_REPLIES_COMMENTS_SUCCESS =
  "GET_FOOTER_REPLIES_COMMENTS_SUCCESS";
export const GET_FOOTER_REPLIES_COMMENTS_FAIL =
  "GET_FOOTER_REPLIES_COMMENTS_FAIL";

export const COMMENT_SUCCESS = "COMMENT_SUCCESS";
export const COMMENT_FAIL = "COMMENT_FAIL";

export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_FAIL = "UPDATE_COMMENT_FAIL";

export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";

export const REPLY_SUCCESS = "REPLY_SUCCESS";
export const REPLY_FAIL = "REPLY_FAIL";

export const UPDATE_REPLY_SUCCESS = "UPDATE_REPLY_SUCCESS";
export const UPDATE_REPLY_FAIL = "UPDATE_REPLY_FAIL";

export const DELETE_REPLY_SUCCESS = "DELETE_REPLY_SUCCESS";
export const DELETE_REPLY_FAIL = "DELETE_REPLY_FAIL";

export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_FAIL = "GET_COMMENT_FAIL";

export const COMMENT_DISCUSSION_SUCCESS = "COMMENT_DISCUSSION_SUCCESS";
export const COMMENT_DISCUSSION_FAIL = "COMMENT_DISCUSSION_FAIL";

export const UPDATE_COMMENT_DISCUSSION_SUCCESS =
  "UPDATE_COMMENT_DISCUSSION_SUCCESS";
export const UPDATE_COMMENT_DISCUSSION_FAIL = "UPDATE_COMMENT_DISCUSSION_FAIL";

export const DELETE_COMMENT_DISCUSSION_SUCCESS =
  "DELETE_COMMENT_DISCUSSION_SUCCESS";
export const DELETE_COMMENT_DISCUSSION_FAIL = "DELETE_COMMENT_DISCUSSION_FAIL";

export const REPLY_DISCUSSION_SUCCESS = "REPLY_DISCUSSION_SUCCESS";
export const REPLY_DISCUSSION_FAIL = "REPLY_DISCUSSION_FAIL";

export const UPDATE_REPLY_DISCUSSION_SUCCESS =
  "UPDATE_REPLY_DISCUSSION_SUCCESS";
export const UPDATE_REPLY_DISCUSSION_FAIL = "UPDATE_REPLY_DISCUSSION_FAIL";

export const DELETE_REPLY_DISCUSSION_SUCCESS =
  "DELETE_REPLY_DISCUSSION_SUCCESS";
export const DELETE_REPLY_DISCUSSION_FAIL = "DELETE_REPLY_DISCUSSION_FAIL";

export const GET_COMMENT_DISCUSSION_SUCCESS = "GET_COMMENT_DISCUSSION_SUCCESS";
export const GET_COMMENT_DISCUSSION_FAIL = "GET_COMMENT_DISCUSSION_FAIL";

export const ADD_NOTIFICATION_SUCCESS = "ADD_NOTIFICATION_SUCCESS";
export const ADD_NOTIFICATION_FAIL = "ADD_NOTIFICATION_FAIL";

export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_FAIL = "GET_NOTIFICATION_FAIL";

export const GET_SEARCH = "GET_SEARCH";
